services:
  traefik:
    container_name: traefik
    image: traefik:v2.9.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cnet-portal:
    ## Uncomment to build from the repository
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: ghcr.io/river-epfl/cnet-data-portal:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cnet_portal.rule=Host(`cnet.local`)"
      - "traefik.http.services.cnet_portal.loadbalancer.server.port=3838"
    environment:
      CNET_ENV: prod
      CNET_DB_HOSTNAME: cnet-db
      CNET_DB_PORT: 3306
      CNET_DB_USERNAME: cnet
      CNET_DB_PASSWORD: cnet
      CNET_DB_NAME: cnet_db
      CNET_NOREPLY_ADDRESS: cnet@noreply.com
      CNET_TO_ADDRESS: cnet@noreply.com
    volumes:
     - ./data:/srv/shiny-server/data
     - ./db_backups:/srv/shiny-server/db_backups
    depends_on:
      - cnet-db

  cnet-db:
    image: mariadb:10.2.41
    environment:
      MYSQL_ROOT_PASSWORD: cnet
      MYSQL_DATABASE: cnet_db
      MYSQL_USER: cnet
      MYSQL_PASSWORD: cnet
    volumes:
      - cnet-mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  cnet-mariadb-data:
