version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.9.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cnet-portal:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cnet_portal.rule=Host(`cnet.local`)"
      - "traefik.http.services.cnet_portal.loadbalancer.server.port=3838"
    environment:
      CNET_ENV: ${CNET_ENV}
      CNET_DB_HOSTNAME: ${CNET_DB_HOSTNAME}
      CNET_DB_PORT: ${CNET_DB_PORT}
      CNET_DB_USERNAME: ${CNET_DB_USERNAME}
      CNET_DB_PASSWORD: ${CNET_DB_PASSWORD}
      CNET_DB_NAME: ${CNET_DB_NAME}
      CNET_NOREPLY_ADDRESS: ${CNET_NOREPLY_ADDRESS}
      CNET_TO_ADDRESS: ${CNET_TO_ADDRESS}
    networks:
      - web
    volumes:
      - ./data:/srv/shiny-server/data
      - ./db_backups:/srv/shiny-server/db_backups
    depends_on:
      - cnet-db

  cnet-db:
    image: mariadb:10.2.41
    environment:
      MYSQL_ROOT_PASSWORD: ${CNET_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CNET_DB_NAME}
      MYSQL_USER: ${CNET_DB_USERNAME}
      MYSQL_PASSWORD: ${CNET_DB_PASSWORD}
    volumes:
      - cnet-mariadb-data:/var/lib/mysql
    networks:
      - web

volumes:
  cnet-mariadb-data:

networks:
  web:
    driver: bridge
